#!/bin/bash

echo "
___  ____ _  _ ____    _ _  _ ____ ___ ____ _    _    ____ ____ 
  /  |___ |  | [__     | |\ | [__   |  |__| |    |    |___ |__/ 
 /__ |___ |__| ___]    | | \| ___]  |  |  | |___ |___ |___ |  \ 
                                                                
"


#This script is for Arch base systems. Manjaro/Arch.
#It's purpose is to install programs that you may find essential.

#functions. Add the commands here

updaterepo () { sudo pacman -Syy; }
updatesystem () { yes | sudo pacman -Syu; }
noanswer () { echo "Skipping..." ; }
chrome () { yes | sudo pacman -S chromium; }
firefox () { yes | sudo pacman -S firefox; }
neofetch () { yes | sudo pacman -S neofetch; }
htop () { yes | sudo pacman -S htop; }
spectacle () { yes | sudo pacman -S spectacle; }
veracrypt () { (echo 1; yes) | yay veracrypt; }
libreoffice () { yes | sudo pacman -S libreoffice-fresh; } 
obs () { yes | sudo pacman -S obs-studio; }


#
#Package and System Update First
#

echo " "
echo "Would you like to update your system? (y/n/e)"
echo "y=yes | n=no | e=exit"
echo " "

read yesorno

if [ "$yesorno" = y ]; then
	updaterepo
elif [ "$yesorno" = y ]; then
	updatesystem
	echo " "
	echo "Update Successful."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi

#
#Chromium Installation
#

echo "Would you like to install Chrome? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	chrome
	echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
	noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi

#
#Firefox Installation
#

echo "Would you like to install Firefox? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	firefox
	echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
	noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
	echo "not a valid answer. Exiting"
	exit 1
fi

#
#Neofetch installation
#

echo "Would you like to install Neofetch? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
        neofetch
	echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
        noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
        echo "not a valid answer. Exiting"
	exit 1
fi

#
#htop Installation
#

echo "Would you like to install htop? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
        htop
        echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
        noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
        echo "not a valid answer. Exiting"
	
fi

#Spectacle (screenshot tool)

echo "Would you like to install Spectacle? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
        spectacle
        echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
        noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
        echo "not a valid answer. Exiting"
fi

#Libreoffice

echo "Would you like to install LibreOffice? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
        libreoffice
        echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
        noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
        echo "not a valid answer. Exiting"
	exit 1
fi

#obs

echo "Would you like to install OBS (Open Broadcast Software)? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
        obs
        echo " "
	echo "Installed Successfully."
	echo " "
elif [ "$yesorno" = n ]; then
        noanswer
	echo " "
elif [ "$yesorno" = e ]; then
	echo "Exiting..."
	exit 1
else
        echo "not a valid answer. Exiting"
	exit 1
fi



echo "Installer Complete. Goodbye!"
